### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by Mrslock** [GraphSAINT/GraphSAINT#10]
Hello, I try to download these datasets from google drive but it is too slow, is there another way to access the datasets?

**Comment by GraphSAINT** [comment]
We are happy to upload the datasets to other locations (e.g., dropbox, ..)

What's your preferred way?

**Comment by Mrslock** [comment]
I will have a try if you can upload the datasets to the dropbox, Many thanks!

**Comment by tedzhouhk** [comment]
We have uploaded the dataset to baiduyun, please check if this helps.
link: https://pan.baidu.com/s/1SOb0SiSAXavwAcNqkttwcg
code: f1ao

**Comment by Mrslock** [comment]
Thanks again!
