### ISSUE TITLE
Performance on citation network

### ISSUE THREAD

**Issue by wzfhaha** [GraphSAINT/GraphSAINT#12]
Hi authors, thanks for making the code public.  I noticed most of the GNNs have evaluated the performance on citation networks, such as Cora, Citeseer and Pubmed.  I also have great interests in the results on Cora, Citeseer and Pubmed. Have you test GraphSAINT on these datasets? Could you report the corresponding results if convenient?  Thanks very much!

**Comment by ZimpleX** [comment]
Thanks for your interests! This is a good suggestion. There are two reasons we didn't use these datasets in the current version of the paper:

1. These graphs are small. We propose GraphSAINT to improve the minibatch performance on large graphs. However, Cora and Citeseer are so small that may not even require a minibatch. 

2. In the current version of GraphSAINT, we focus on the inductive learning setting. While it is straightforward to extend to transductive learning (e.g., by masking the minibatch nodes with label in classifier layer), we leave it as future work. 

We may add results on these popular datasets in our next version of the paper. For now, we haven't tried them so I couldn't give you a performance estimation.
