### ISSUE TITLE
how to generate my own dataset

### ISSUE THREAD

**Issue by SakerLiu** [GraphSAINT/GraphSAINT#13]
The idea is good, while I want to test the algorithm on transductive dataset, such as 'cora', can you give a generator script

**Comment by ZimpleX** [comment]
Thanks for your interest! This is a good suggestion. Given our current schedule, we will probably provide the script during summer. However, please note that Cora is a very small graph, and minibatch training may not be beneficial in this case. 

We will also update the README in a few days to include the details of preparing your own datasets. 

In the meantime, please note that GraphSAINT has also been included in the [PyTorch Geometric](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.GraphSAINTSampler) library (although we haven't got a chance yet to verify its implementation details). You can try using that library if their dataset format fits your need.
