### ISSUE TITLE
About Flickr Dataset

### ISSUE THREAD

**Issue by thematrixduo** [GraphSAINT/GraphSAINT#15]
Might be a stupid question but it seems to be that the Flickr Dataset contains a single graph where you have train/val/test masks covering different nodes. How do you ensure this is the inductive learning setting where during training the sampled neighbours does not contain nodes from val/test splits?

**Comment by ZimpleX** [comment]
Thanks for your interest! This is somehow relevant to our issue #1. 

Even though the shapes of adj_train and adj_full are the same, we only keep the train-to-train connections in adj_train. The sampling during minibatch training is performed on adj_train only. Therefore, none of the feature, label or connection information of the val/test sets are seen in the training process -- conforming to the "inductive" setting. 

The fact that adj_train and adj_full are of the same shape means adj_train contains some all-zero rows/cols corresponding to the val/test nodes. Although those rows/cols will never be touched during training, we still keep them in the sparse adj_train, just to avoid re-indexing the training nodes (for ease of implementation). 

Thanks for pointing this our. We will clarify this in README.

**Comment by thematrixduo** [comment]
OK I see, thanks!
