### ISSUE TITLE
globals.py Line 41, a minor mistake

### ISSUE THREAD

**Issue by hyclex** [GraphSAINT/GraphSAINT#17]
Should it be

-(-200 // NUM_PAR_SAMPLER) ?

**Comment by ZimpleX** [comment]
Maybe I missed your point, but it is "-(-200 // NUM_PAR_SAMPLER)" in the current version. 

"-(-200 // NUM_PAR_SAMPLER)" is equivalent to math.ceil(200/NUM_PAR_SAMPLER).

**Comment by hyclex** [comment]
I double checked your code. Your current version is 
-(-(200 // NUM_PAR_SAMPLER)), which does not do the ceiling.

**Comment by ZimpleX** [comment]
Ahh, sorry. My bad.

 You are right. Thanks for pointing this out! I've pushed a fix.
