### ISSUE TITLE
Clarification: Does this model use neighbor labels as inputs?

### ISSUE THREAD

**Issue by omgmax** [GraphSAINT/GraphSAINT#25]
Hi thank you for your work.

I have a clarification question: I'm aware that the features of neighbor are used as inputs for node classification. I'm wondering if neighbor labels are also used as inputs for the algorithm.

Thank you so much!

**Comment by ZimpleX** [comment]
For the current version, we don't use labels as the inputs. But I think the minibatch algorithm should be able to support this.

**Comment by omgmax** [comment]
Thanks again for the reply!
