### ISSUE TITLE
Code to make .bin files

### ISSUE THREAD

**Issue by wohlbier** [GraphSAINT/GraphSAINT#33]
Hi,
Do you have code to convert data to the `*.bin` format used in the `ipdps19_cpp` folder? The `README.md` in that folder says to use the `convert.py` script, but that script does not generate those files. Thanks.
jgw

**Comment by tedzhouhk** [comment]
Hi Jgw,

I have added the script to generate the binary files. Please check `./ipdps19_cpp/convert.py`.

**Comment by wohlbier** [comment]
Thanks!
