### ISSUE TITLE
No Cuda GPUs availables

### ISSUE THREAD

**Issue by sandl99** [GraphSAINT/GraphSAINT#35]
Hi,
I am trying to implement sample subgraph for recommendation with knowledge graph using GraphSAINT. 
I write a print code `print(torch.cuda.is_available())`  in __init__() function of Minibatch class. 
It printed `True` when I ran train.py but it printed `False` when I ran from Minibatch. 
I guess the problem here from `from graphsaint.graph_samplers import *`.
Can you clarify it for me?

**Comment by tedzhouhk** [comment]
Hi sandl99,
I am not sure how do you run from Minibatch but I guess it's because you import globals.py. In globals.py, we select GPU by changing the environment variable "CUDA_VISIBLE_DEVICES". Can you try again with the flag "--gpu <gpu you want to use>" added?

**Comment by sandl99** [comment]
Oh, I just write main function out of class Minibatch and print it. I think you are right. 
It's late to check. I'll check that tomorrow and reply you later.
Thank you for your answer.
