### ISSUE TITLE
Unsupervised: Learning node representations on datasets without class labels?

### ISSUE THREAD

**Issue by akhilarora** [GraphSAINT/GraphSAINT#37]
I am curious whether there exists a possibility of learning node representations without supervised class label information, similar to other implementations of GCNs such as GraphSAGE?

**Comment by XueniLuo** [comment]
Hi, from my point of view, GraphSAINT is perfect for unsupervised learning. It can combine with any pseudo-label based self-learning solutions, such as DGI. If you generate pseudo-labels based on subgraphs, that works. My recent job is an unspervised graph representation learning method which was accepted by CIKM2021, and GraphSAINT is one of the tricks I used.  If you are interested, this is the name of my paper "Leveraging Domain Information to Classify Financial Documents via Unsupervised Graph Momentum Contrast", and the conference will be hosted on 1-5 November 2021, Online. Hope this would help.

**Comment by ZimpleX** [comment]
Hi Xueni,

Thanks for the pointer! I'm glad that GraphSAINT can be helpful for the unsupervised / self-supervised tasks. What you described makes perfect sense to me. It seems that your paper is not available online yet, so I'm looking forward to the conference presentation in Nov. 

Good luck with the presentation!

**Comment by XueniLuo** [comment]
> Hi Xueni,
> 
> Thanks for the pointer! I'm glad that GraphSAINT can be helpful for the unsupervised / self-supervised tasks. What you described makes perfect sense to me. It seems that your paper is not available online yet, so I'm looking forward to the conference presentation in Nov.
> 
> Good luck with the presentation!

Hi, Hanqing.

So exciting to have your reply, your work helped me a lot, the subgraph sampling schema and normalization terms improve the performances of my unsupervised model. 

I'll keep tracking your new work, I really appreciate your study.

Have a nice life~

**Comment by nodiz** [comment]
Hi @ZimpleX, has this extension been added to the repo?
