### ISSUE TITLE
question about the computation of loss_norm

### ISSUE THREAD

**Issue by initzhang** [GraphSAINT/GraphSAINT#38]
according to the paper, loss_norm(v) = C(v) / N, where N is the number of subgraphs and C(v) is the appearance times of v in all subgraphs. While In the pytorch implementation I found the actual computation is different
https://github.com/GraphSAINT/GraphSAINT/blob/7386fe58c4c10873f3ba7ada22bffa8c413c6392/graphsaint/pytorch_version/minibatch.py#L210

I know for convenience we calculate the reciprocal instead, but the above two still show conflict(specifically, in the code you added another `self.node_train.size`), is there something that I misunderstanding? Thank you!

**Comment by tedzhouhk** [comment]
Hi Initzhang, the loss normalization ![formula](https://render.githubusercontent.com/render/math?math=\lambda_v=C(v)/N) is applied to the minibatch loss by ![formula](https://render.githubusercontent.com/render/math?math=L_{batch}=\Sigma_{}L_v/\lambda_v) (Equation 3 in our ICLR paper).

In the code, the norm_loss is feed to the loss term as weights.That's why we calculate the reciprocal instead. https://github.com/GraphSAINT/GraphSAINT/blob/7386fe58c4c10873f3ba7ada22bffa8c413c6392/graphsaint/pytorch_version/models.py#L125-L130

**Comment by initzhang** [comment]
Hi tedzhouhk, thanks for your reply!

Yes I understand that you calculate the reciprocal so that norm_loss can be treated as weights conveniently. While my question is about the calculation of <img src="https://render.githubusercontent.com/render/math?math=\lambda_{v}">

In the [ICLR2020 paper](https://arxiv.org/pdf/1907.04931.pdf), section 3.2 shows that <img src="https://render.githubusercontent.com/render/math?math=\lambda_{v}=|\mathcal{V}| \cdot p_{v}"> , and its estimation <img src="https://render.githubusercontent.com/render/math?math=\lambda_{v}=\frac{C_v}{N}"> . But in the code, you calculate <img src="https://render.githubusercontent.com/render/math?math=\text{norm\_loss}=\frac{1}{\lambda_v} = \frac{N}{C_v \cdot |\mathcal{V}|}">.  The code does not comply with the paper.
https://github.com/GraphSAINT/GraphSAINT/blob/7386fe58c4c10873f3ba7ada22bffa8c413c6392/graphsaint/pytorch_version/minibatch.py#L210

From my understanding, actually <img src="https://render.githubusercontent.com/render/math?math=p_{v} \approx \frac{C_v}{N}">, bringing it to <img src="https://render.githubusercontent.com/render/math?math=\lambda_{v}=|\mathcal{V}| \cdot p_{v}">, we have <img src="https://render.githubusercontent.com/render/math?math=\lambda_{v}=\frac{|\mathcal{V}| \cdot C_v}{N} ">, then <img src="https://render.githubusercontent.com/render/math?math=\text{norm\_loss}=\frac{1}{\lambda_v} = \frac{N}{C_v \cdot |\mathcal{V}|}"> just complies with the code. Is this a typo in the arxiv version?

**Comment by ZimpleX** [comment]
Hi initzhang, 

You are right. This is indeed a typo in the ICLR 2020 paper. 

In line 3 of [page 5](https://arxiv.org/pdf/1907.04931.pdf), ![formula1](https://render.githubusercontent.com/render/math?math=\lambda_v=\frac{C_v}{N}) should be corrected to ![formula1](https://render.githubusercontent.com/render/math?math=\lambda_v=\frac{|\mathcal{V}|\cdot%20C_v}{N}). 

Thanks for your careful reading on our paper. We appreciate the feedback!

Hanqing

**Comment by initzhang** [comment]
Hi Hanqing, 
Got it, thanks for reply!
