### ISSUE TITLE
Can the code run on tensorflow2?

### ISSUE THREAD

**Issue by HenryYuen128** [GraphSAINT/GraphSAINT#40]

**Comment by ZimpleX** [comment]
Our current version only runs on TF v1. We are interested in providing a TF v2 version, but we currently don't have a specific timeline yet. 

If you are in urgent need of TF v2 version of GraphSAINT, you may try the automatic upgrading tool provided by TensorFlow: 

https://www.tensorflow.org/guide/migrate/upgrade

Thanks!
