### ISSUE TITLE
Problems of cython samplers compling

### ISSUE THREAD

**Issue by coderhaohao** [GraphSAINT/GraphSAINT#5]
When we compile the cython sampler, at the root path of GraphSAINT. On my Macbook and Ubuntu server, this process cannot be completely done. When running the sh file, python reports the missing of the graphsaint.cython_sampler. I want to make sure that what we should do to run the code.
Detail errors are listed below:
Mac Os:
$ python graphsaint/setup.py build_ext --inplace
Compiling graphsaint/cython_sampler.pyx because it changed.
Compiling graphsaint/cython_utils.pyx because it changed.
Compiling graphsaint/norm_aggr.pyx because it changed.
[1/3] Cythonizing graphsaint/cython_sampler.pyx
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
[2/3] Cythonizing graphsaint/cython_utils.pyx
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
[3/3] Cythonizing graphsaint/norm_aggr.pyx
warning: graphsaint/norm_aggr.pyx:24:17: Use boundscheck(False) for faster access
warning: graphsaint/norm_aggr.pyx:24:35: Use boundscheck(False) for faster access
warning: graphsaint/norm_aggr.pyx:24:51: Use boundscheck(False) for faster access
running build_ext
building 'graphsaint.cython_sampler' extension
creating build
creating build/temp.macosx-10.7-x86_64-3.6
creating build/temp.macosx-10.7-x86_64-3.6/graphsaint
g++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/anaconda3/include/python3.6m -c graphsaint/cython_sampler.cpp -o build/temp.macosx-10.7-x86_64-3.6/graphsaint/cython_sampler.o -fopenmp -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                 from /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                 from /anaconda3/include/python3.6m/Python.h:11,
                 from graphsaint/cython_sampler.cpp:25:
/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.

Ubuntu:
python graphsaint/setup.py build_ext --inplace
Compiling graphsaint/cython_sampler.pyx because it changed.
Compiling graphsaint/cython_utils.pyx because it changed.
Compiling graphsaint/norm_aggr.pyx because it changed.
[1/3] Cythonizing graphsaint/cython_sampler.pyx
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
[2/3] Cythonizing graphsaint/cython_utils.pyx
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:28:29: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
warning: graphsaint/cython_utils.pxd:33:31: Buffer unpacking not optimized away.
[3/3] Cythonizing graphsaint/norm_aggr.pyx
warning: graphsaint/norm_aggr.pyx:24:51: Use boundscheck(False) for faster access
warning: graphsaint/norm_aggr.pyx:24:35: Use boundscheck(False) for faster access
warning: graphsaint/norm_aggr.pyx:24:17: Use boundscheck(False) for faster access
running build_ext
building 'graphsaint.cython_sampler' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/graphsaint
g++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/chen/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/chen/anaconda3/include/python3.7m -c graphsaint/cython_sampler.cpp -o build/temp.linux-x86_64-3.7/graphsaint/cython_sampler.o -fopenmp -std=c++11
unable to execute 'g++': No such file or directory
error: command 'g++' failed with exit status 1

**Comment by GraphSAINT** [comment]
For the compilation on Mac, are you using MacOS Majove? If so, maybe the following link helps:

https://github.com/qutip/qutip/issues/1030

**Comment by coderhaohao** [comment]
Thanks for your replay. How about the compiling on the Ubuntu server? To me, it's more serious.

**Comment by GraphSAINT** [comment]
For the error on Ubuntu: It doesn't seem to me that it is `cython_sampler.cpp` that is missing, since `cython_sampler.cpp` should be generated from compiling `cython_sampler.pyx`. Just to double check:

1. Have you installed all the packages listed in `README`?
2. Have you checked if `/home/chen/anaconda3/lib/python3.7/site-packages/numpy/core/include` is the correct path to you `numpy`?

We have successfully compiled on Ubuntu, so we may need more information from you to identify the problem.

**Comment by coderhaohao** [comment]
Thanks for your advice, my docker was not compiled with the g++ item. After fixed it, your compiling code works.
