### ISSUE TITLE
Questions regarding Amazon dataset

### ISSUE THREAD

**Issue by NIRVANALAN** [GraphSAINT/GraphSAINT#8]

**Comment by NIRVANALAN** [comment]
Hi, thanks for your outstanding work first.

I have a question about the dataset you used and could you help me with this. What's the original version of Amazon Dataset you used in your paper, and is this comparable to the Amazon2M proposed by Cluster-GCN paper? They generated their dataset from Amazon3M and I wonder if that's the dataset you used in your experiments.

**Comment by ZimpleX** [comment]
Hi, thanks for your interest in our work. 

The raw data of Amazon was provided by our funding agency. So we didn't download from the website that Cluster-GCN refers to. However, the descriptions of the datasets indeed sound quite similar -- Both are co-purchasing graphs, and both use bag-of-word as the raw feature. 

Regarding whether these two datasets are comparable: While the data are of similar characteristics, I would not recommend directly compare the accuracy numbers. GraphSAINT and Cluster-GCN use different dimensions when performing PCA on the raw feature (200 vs. 100). We also use different sets of top-occurring categories as the labels (set of size 107 vs. set of size 47).

We'll double-check if the raw data are coming from the same source and get back to you in couple of days. We'll also upload the raw data and prepare the necessary documentation soon (probably in Feb).

**Comment by NIRVANALAN** [comment]
Thanks very much~

**Comment by GraphSAINT** [comment]
We have prepared a document for explaining the dataset pre-processing procedure (./dataset_details.md). I believe the raw Amazon data of GraphSAINT and Cluster-GCN are different. Specifically, our raw features are length-100k sparse 4-grams.

**Comment by NIRVANALAN** [comment]
Thanks for your double-check and replying after such a long time;
I ll check more details in your document and return to you if I have more questions
