### ISSUE TITLE
Bad performance of Vanilla GCN

### ISSUE THREAD

**Issue by NIRVANALAN** [GraphSAINT/GraphSAINT#9]
Hi! I observed in your Amazon Dataset the performance of Vanilla GCN and FastGCN is poor compared to other models, and I didn't find relevant explanation in your paper. Also, you mentioned in the Appendix that you set the Batch Size of vanilla GCN, does that mean you use the  gcn-aggregator  
 of graphsage?

I am trying to understand why does gcn model perform so poor on large graph, can the reason be attributed to SGD/BGD has better generalization ability compared to full graph gradient decent? Could you help me with that?

**Comment by ZimpleX** [comment]
These are good observations. 

**[Vanilla GCN]**: Yes, we use the batched version of vanilla GCN implemented in the GraphSAGE repo (also see Table 4 in appendix). On large graphs like Amazon, full-batch training not only converges much slower, but also has high (and impractical) memory requirement. 

**[FastGCN]**: The poor performance of FastGCN on large graphs such as Yelp and Amazon is expected. The layer-wise independent node sampling of FastGCN results in very sparse connection in the minibatch. In fact, considering that the previous layer samples are not a superset of the next layer samples, the minibatch can even be disconnected (i.e., a node in the next layer has neither neighbor connection nor self connection in the previous layer). We give a simple analysis for the layer-wise independent edge sampling in the "Remark" paragraph of Section 3.3. The situation for layer-wise independent node sampling should be similar. The above gives a key differentiation between layer-sampling and graph-sampling techniques. 

**[Poor performance of Vanilla GCN]**: Frankly, we don't have a definite answer to explain why Vanilla GCN performs poor on Amazon (and also Yelp). I just have some observations and guess. 

- First of all, the key difference between vanilla GCN and GraphSAGE minibatches is in the neighborhood sizes. From the convergence curves, one would guess a too high neighbor expansion factor may be harmful. I feel that this inherently connects back to the over-smoothening phenomenon. Imagine that a node in the output layer expands 10000 neighbors in the input layer. So features of that 10000 nodes averages out to be the feature of this single output node. Eventually, the optimizer may have a hard time learning features at the granularity of a node. 

I did a simple testing for the three large graphs (Reddit, Yelp and Amazon). For a batch of 512, without any sampling, distinct number of 2-hop neighbors per minibatch root are around 280, 280, 1200 for Reddit, Yelp, Amazon. This may partially explain the vanilla GCN performance on Amazon.

- The number of distinct 2-hop neighbors are similar for Reddit and Yelp. However, vanilla GCN performs much worse on Yelp. Looking at Table 1 and Figure 5, I notice that Yelp has much lower average degree and much uneven distribution of degrees than Reddit. If Yelp and Reddit have the same number of distinct 2-hop neighbors, this means at hop 2, the connections are concentrated to the small set of high degree nodes of Yelp, no matter how you pick the roots. The optimizer may turn out to learn similar features from different batches, even though the roots of the batches are quite different. Intuitively, even the simple random sampling may prevent the optimizer from just learning the "global" features. 

Here's how I count the number of distinct 2-hop neighbors:

```
num_v = adj.shape[0]

cnt_uniq_neigh_2 = []
for run in range(20):
    neigh = np.zeros(num_v)
    v_batch = np.random.randint(0,num_v,size=batch)
    for v in v_batch:
        v_neighs = adj.indices[adj.indptr[v]:adj.indptr[v+1]]
        for n in v_neighs:
            nn = adj.indices[adj.indptr[n]:adj.indptr[n+1]]
            neigh[nn] = 1
    cnt_uniq_neigh_2.append(np.where(neigh==1)[0].size)
avg_neigh2 = sum(cnt_uniq_neigh_2)/len(cnt_uniq_neigh_2)
```

There could be other explanations. Further discussions are more than welcome.

**Comment by ZimpleX** [comment]
These are good observations.

[Vanilla GCN]: Yes, we use the batched version of vanilla GCN. On large graphs like Amazon, full-batch training not only converges much slower, but also has high (and impractical) memory requirement.

[FastGCN]: The poor performance of FastGCN on large graphs such as Yelp and Amazon is expected. The layer-wise independent node sampling of FastGCN results in very sparse connection in the minibatch. In fact, considering that the previous layer samples are not a superset of the next layer samples, the minibatch can even be disconnected (i.e., a node in the next layer has neither neighbor connection nor self connection in the previous layer). We give a simple analysis for the layer-wise independent edge sampling in the "Remark" paragraph of Section 3.3. The situation for layer-wise independent node sampling should be similar. The above gives a key differentiation between layer-sampling and graph-sampling techniques.

[Poor performance of Vanilla GCN]: We are doing some additional testing. We'll get back to you soon.
